language: generic
sudo: false
before_install:
  - 'wget https://github.com/FPtje/GLuaFixer/releases/download/1.11.1/glualint-1.11.1-linux-stripped.zip'
  - 'unzip $PWD/glualint-1.11.1-linux-stripped.zip'
  - 'chmod +x $PWD/glualint'
install: true
script:
  - 'find lua -type f -not -path "lua/sgrf/server/lib/*" -exec $PWD/glualint {} + | tee output.txt'
  - 'if [ $(grep "\[Error\]" "$PWD/output.txt" | wc -w) != "0" ]; then return 1; else return 0; fi;'
